name: Korve Media
favicon: null
layout_spectrum: 0.7336513048503548
typography_spectrum: 0.7693805939052254
title: Korve Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff9016'
    - '#ffff00'
    - '#ff0000'
    - '#ff5500'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
